#!/bin/bash

alias g='git'
alias gst='git status'
alias gco='git checkout'
alias ga='git add'
alias gd='git diff'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gs='git stash'
alias glg='git log --pretty=format:"%C(magenta)%h%Creset -%C(red)%d%Creset %s %C(dim green)(%cr) [%an]" --abbrev-commit -30'

alias rm='echo maybe use tp instead; rm -i'
alias mv='mv -i'
alias ln='ln -i'
alias cp='cp -i'
alias md='mkdir -p'
alias ls='ls --color=auto'
alias ll='ls -alhF --time-style=long-iso --color=auto'
alias tp='trash-put'
alias xc='xclip -selection clipboard'

alias v=vi
alias l=lvim
alias a='NVIM_APPNAME=astronvim nvim'
alias c=code
alias c.='code .'

alias k=exa
alias kc='exa -abhgHliS'
alias fd='fdfind'
alias bat='batcat'

alias tu='tmux -u'
alias mpc=multipass
alias db=distrobox
alias dbm='distrobox enter main'
alias h=distrobox-host-exec
alias tb=toolbox
alias tbm='toolbox enter main'
alias d=docker
alias dc=docker-compose
alias ap=ansible-playbook

alias di='docker images'
alias dps='docker ps'
alias dex='docker exec'
alias drun='docker run'
alias dl='docker logs'
alias dstop='docker stop'
alias drm='docker rm'
alias drmi='docker rmi'

alias fp=flatpak

alias i='sudo apt install -y'
alias u='sudo apt update && sudo apt upgrade -y'
alias up='u && sudo apt upgrade -y && snap refresh && flatpak update -y'
alias di='sudo dpkg -i'
alias sd='poweroff || shutdown now || sudo shutdown now'
alias ipa='ip a | grep -E "(192|172)"'
